### ISSUE TITLE
ZC158: --> PHP Notice: Undefined index: products_id in zcDPU_Ajax.php on line 691.

### ISSUE THREAD

**Issue by torvista** [Zen4All-nl/Zen-Cart-Dynamic-Price-Updater#10]
Product with attributes: debug created on each attribute change or page refresh.
line is
`    $page = zen_get_info_page((int)$_GET['products_id']);`

It appears that neither this nor $_SESSION['products_id'] is set at this point.

**Comment by Zen4All** [comment]
Thanks, I have not tested on ZC158 yet. Ill see if I have time for that next week.

**Comment by torvista** [comment]
Note that outputting $_GET at this point results in :

> $_GET:
> Array
> (
>     [act] => DPU_Ajax
>     [method] => getDetails
>     [main_page] => index
> )
>

**Comment by torvista** [comment]
Its in the POST. This works

    $page = zen_get_info_page((int)$_POST['products_id']);

**Comment by torvista** [comment]
Fixed in
https://github.com/Zen4All-nl/Zen-Cart-Dynamic-Price-Updater/pull/15/commits/4350ef093c90fad40ee10344bb8b5c6f1e5d72d8
