### ISSUE TITLE
Develop: Rounding error on attribute price display

### ISSUE THREAD

**Issue by torvista** [Zen4All-nl/Zen-Cart-Dynamic-Price-Updater#13]
Default currency Euro.
Show prices with tax.
Worldwide tax rate of 21%.
Product priced by attribute, base price 0.
Attributes prices none, at
 12.3884, 8.2562 default 5.7851

Attributes prices are listed correctly, but selecting the 7 gives 7.01.
![Clipboard01](https://user-images.githubusercontent.com/4391026/102021139-0db3e880-3d7e-11eb-96fe-890d585f9229.gif)

I know the rounding issue is a very long one in core code, but it will be solved one day and I'd prefer to see that day dawn soon!
If this is core, I'll push it over there.

**Comment by Zen4All** [comment]
Yes, I agree, but I think this should be solve in ZC core first.

**Comment by torvista** [comment]
In truth the only reason I started reviewing this mod was to fix this long-standing irritation...it took me two weeks of no spare time to realise it was a core issue!
