### ISSUE TITLE
zcDPU_Ajax: function setCurrentPage() - why?

### ISSUE THREAD

**Issue by torvista** [Zen4All-nl/Zen-Cart-Dynamic-Price-Updater#16]
I don't see the point of this function within DPU. It just writes to whos_online.

Why?

**Comment by Zen4All** [comment]
Don't know, will look in to it

**Comment by Zen4All** [comment]
Looks like it is safe to remove the function from the module

**Comment by torvista** [comment]
ok, thanks!
