### ISSUE TITLE
autoload of on_load_dpu.js

### ISSUE THREAD

**Issue by torvista** [Zen4All-nl/Zen-Cart-Dynamic-Price-Updater#7]
Hi,
what is the point of this?
what init(); is it referencing? - I don't see any function init on the catalog-side... only the admin side.

**Comment by Zen4All** [comment]
Hi, it is better to as @mc12345678 , as he has done the latest development on this mod. You should open an issue at https://github.com/mc12345678/Dynamic_Price_Updater

**Comment by torvista** [comment]
ok
